#!/bin/bash

# validate-before-commit.sh
# PreToolUse Hook: git commit 명령 감지 시 빌드/타입/테스트 게이트
# 모든 검증 통과 시에만 커밋 허용 (exit 0), 실패 시 차단 (exit 2)

# jq 없으면 python3 폴백
if ! command -v jq &>/dev/null; then
  jq() {
    python3 -c "
import sys, json
data = json.load(sys.stdin)
path = sys.argv[1].lstrip('.').split('.')
for key in path:
    key = key.split('//')[0].strip()
    data = data.get(key, '') if isinstance(data, dict) else ''
print(data if data else '')
" "$@"
  }
fi

# stdin에서 JSON 입력 읽기
INPUT=$(cat)

TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')
COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty')

# Bash 도구의 git commit 명령만 필터링
if [ "$TOOL_NAME" != "Bash" ]; then
  exit 0
fi

if ! echo "$COMMAND" | grep -q "git commit"; then
  exit 0
fi

# --allow-empty, merge commit, amend는 스킵
if echo "$COMMAND" | grep -qE "(--allow-empty|--amend|merge)"; then
  exit 0
fi

# --- 커밋 메시지 포맷 검증 ---
# -m "메시지" 에서 메시지 추출
COMMIT_MSG=$(echo "$COMMAND" | sed -n 's/.*-m ["\x27]\(.*\)["\x27].*/\1/p')
if [ -n "$COMMIT_MSG" ]; then
  # 빈 메시지 차단
  if [ ${#COMMIT_MSG} -lt 3 ]; then
    echo "  x 커밋 메시지가 너무 짧습니다 (최소 3자)" >&2
    exit 2
  fi
  # AI 관련 메시지 차단 (사용자 규칙)
  if echo "$COMMIT_MSG" | grep -qiE "^(AI|Codex|GPT|LLM|generated by)"; then
    echo "  x 커밋 메시지에 AI 관련 내용 포함 금지" >&2
    exit 2
  fi
fi

# --- 적응형 3-tier 검증 시스템 ---

# 1. 스테이징된 파일 목록 수집
STAGED_FILES=$(git diff --cached --name-only 2>/dev/null)
if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

FILE_COUNT=$(echo "$STAGED_FILES" | wc -l | tr -d ' ')

# 2. 코드 파일 여부 판별 (확장자 기반)
CODE_EXTENSIONS="ts|tsx|js|jsx|py|dart|java|go|rs|rb|php|swift|kt|c|cpp|h|html|vue|svelte"
HAS_CODE=0
while IFS= read -r file; do
  if echo "$file" | grep -qE "\.($CODE_EXTENSIONS)$"; then
    HAS_CODE=1
    break
  fi
done <<< "$STAGED_FILES"

# 3. 보안/아키텍처 패턴 감지 (파일명/디렉토리명의 단어 경계 매칭)
HAS_SECURITY=0
HAS_ARCHITECTURE=0
while IFS= read -r file; do
  # 보안: .env 파일, 또는 경로 구성요소에 보안 키워드 포함
  if echo "$file" | grep -qE "\.env(\.|$)"; then
    HAS_SECURITY=1
  fi
  BASENAME=$(basename "$file")
  if echo "$BASENAME" | grep -qiE "^(auth|secret|credential|permission)[^a-z]|[^a-z](auth|secret|credential|permission)"; then
    HAS_SECURITY=1
  fi
  # 아키텍처: 디렉토리명이 정확히 매칭 또는 파일명이 키워드로 시작
  if echo "$file" | grep -qiE "(^|/)migrations?/|(^|/)middleware/|(^|/)routes?/|(^|/)schemas?/"; then
    HAS_ARCHITECTURE=1
  fi
  if echo "$BASENAME" | grep -qiE "^(schema|migration|middleware)\.(ts|js|py|dart|sql)$"; then
    HAS_ARCHITECTURE=1
  fi
done <<< "$STAGED_FILES"

# 4. 티어 결정
TIER="STANDARD"

# LIGHT: 비코드 파일만 + 3개 이하
if [ "$HAS_CODE" -eq 0 ] && [ "$FILE_COUNT" -le 3 ]; then
  TIER="LIGHT"
fi

# THOROUGH: 보안/아키텍처 파일 포함 또는 10개 초과
if [ "$HAS_SECURITY" -eq 1 ] || [ "$HAS_ARCHITECTURE" -eq 1 ] || [ "$FILE_COUNT" -gt 10 ]; then
  TIER="THOROUGH"
fi

echo "[검증 티어: $TIER] (파일 ${FILE_COUNT}개)" >&2

# LIGHT 티어: 즉시 통과
if [ "$TIER" = "LIGHT" ]; then
  echo "  o 비코드 파일만 변경 - 검증 스킵" >&2
  exit 0
fi

# --- 티어별 검증 실행 ---

GATE_FAILED=0
ERRORS=""

# 프로젝트 유형 감지
IS_NODE=0
IS_FLUTTER=0
[ -f "package.json" ] && IS_NODE=1
[ -f "pubspec.yaml" ] && IS_FLUTTER=1

# === Node.js 프로젝트 검증 ===
if [ "$IS_NODE" -eq 1 ]; then

  # [STANDARD + THOROUGH] 타입 체크
  if grep -q '"type-check"' package.json 2>/dev/null; then
    echo "  [타입체크] TypeScript 검증 중..." >&2
    TYPE_OUTPUT=$(npm run type-check 2>&1)
    if [ $? -ne 0 ]; then
      GATE_FAILED=1
      ERRORS+="[TYPE ERROR]\n$(echo "$TYPE_OUTPUT" | grep -E "error TS" | head -10)\n\n"
      echo "  x 타입 체크 실패" >&2
    else
      echo "  o 타입 체크 통과" >&2
    fi
  fi

  # [THOROUGH only] 빌드 체크
  if [ "$TIER" = "THOROUGH" ]; then
    if grep -q '"build"' package.json 2>/dev/null; then
      echo "  [빌드] 빌드 검증 중..." >&2
      BUILD_OUTPUT=$(npm run build 2>&1)
      if [ $? -ne 0 ]; then
        GATE_FAILED=1
        ERRORS+="[BUILD ERROR]\n$(echo "$BUILD_OUTPUT" | tail -20)\n\n"
        echo "  x 빌드 실패" >&2
      else
        echo "  o 빌드 통과" >&2
      fi
    fi

    # [THOROUGH only] 테스트 실행
    if grep -q '"test"' package.json 2>/dev/null; then
      TEST_SCRIPT=$(node -e "const p=require('./package.json'); console.log(p.scripts?.test || '')" 2>/dev/null)
      if [ -n "$TEST_SCRIPT" ] && ! echo "$TEST_SCRIPT" | grep -qE "^(echo|exit|no test)"; then
        echo "  [테스트] 테스트 실행 중..." >&2
        TEST_OUTPUT=$(timeout 120 npm test -- --run 2>&1 || timeout 120 npm test 2>&1)
        if [ $? -ne 0 ]; then
          GATE_FAILED=1
          ERRORS+="[TEST ERROR]\n$(echo "$TEST_OUTPUT" | tail -20)\n\n"
          echo "  x 테스트 실패" >&2
        else
          echo "  o 테스트 통과" >&2
        fi
      fi
    fi
  fi
fi

# === Flutter 프로젝트 검증 ===
if [ "$IS_FLUTTER" -eq 1 ]; then

  # [STANDARD + THOROUGH] flutter analyze
  echo "  [분석] Flutter analyze 실행 중..." >&2
  ANALYZE_OUTPUT=$(flutter analyze 2>&1)
  if [ $? -ne 0 ]; then
    GATE_FAILED=1
    ERRORS+="[FLUTTER ANALYZE]\n$(echo "$ANALYZE_OUTPUT" | tail -15)\n\n"
    echo "  x Flutter analyze 실패" >&2
  else
    echo "  o Flutter analyze 통과" >&2
  fi

  # [THOROUGH only] flutter test
  if [ "$TIER" = "THOROUGH" ]; then
    echo "  [테스트] Flutter test 실행 중..." >&2
    FTEST_OUTPUT=$(flutter test 2>&1)
    if [ $? -ne 0 ]; then
      GATE_FAILED=1
      ERRORS+="[FLUTTER TEST]\n$(echo "$FTEST_OUTPUT" | tail -15)\n\n"
      echo "  x Flutter test 실패" >&2
    else
      echo "  o Flutter test 통과" >&2
    fi
  fi
fi

# === Supabase Edge Function 변경 감지 ===
HAS_EDGE_FN=0
EDGE_FN_FILES=""
while IFS= read -r file; do
  if echo "$file" | grep -qE "^supabase/functions/.*/index\.ts$"; then
    HAS_EDGE_FN=1
    EDGE_FN_FILES+="$file "
  fi
done <<< "$STAGED_FILES"

if [ "$HAS_EDGE_FN" -eq 1 ]; then
  echo "" >&2
  echo "  ⚠ [Edge Function 변경 감지] $EDGE_FN_FILES" >&2
  echo "    커밋 후 반드시 배포하세요:" >&2
  echo "    npx supabase functions deploy <name> --no-verify-jwt" >&2
  echo "" >&2
fi

# === HTML 프론트엔드 검증 (public/*.html 변경 시) ===
HAS_HTML=0
HTML_FILES=""
while IFS= read -r file; do
  if echo "$file" | grep -qE "^public/.*\.html$"; then
    HAS_HTML=1
    HTML_FILES+="$file "
  fi
done <<< "$STAGED_FILES"

if [ "$HAS_HTML" -eq 1 ]; then
  echo "  [HTML] 프론트엔드 파일 변경 감지: $HTML_FILES" >&2

  # 1. HTML 구문 오류 체크 (script 태그 닫힘, 기본 구조)
  for hf in $HTML_FILES; do
    if [ -f "$hf" ]; then
      # script 태그 열림/닫힘 수 비교
      OPEN_SCRIPT=$(grep -c "<script" "$hf" 2>/dev/null || echo 0)
      CLOSE_SCRIPT=$(grep -c "</script>" "$hf" 2>/dev/null || echo 0)
      if [ "$OPEN_SCRIPT" -ne "$CLOSE_SCRIPT" ]; then
        GATE_FAILED=1
        ERRORS+="[HTML SYNTAX] $hf: <script> 태그 불일치 (열림:$OPEN_SCRIPT, 닫힘:$CLOSE_SCRIPT)\n\n"
        echo "  x $hf: script 태그 불일치" >&2
      fi

      # Supabase RPC 호출이 있으면 함수명 존재 여부 경고
      RPC_CALLS=$(grep -oE "rpc\(['\"][^'\"]+['\"]" "$hf" 2>/dev/null | sed "s/rpc(['\"]//;s/['\"]//")
      if [ -n "$RPC_CALLS" ]; then
        echo "  i $hf: RPC 함수 호출 감지: $RPC_CALLS" >&2
        echo "  ⚠ 배포 전 브라우저에서 RPC 응답 확인 필수!" >&2
      fi
    fi
  done

  # 2. Vercel 배포 예정이면 경고
  echo "" >&2
  echo "  ⚠ [HTML 변경 감지] 커밋 후 배포 전에 반드시:" >&2
  echo "    1. 로컬에서 브라우저 열어서 확인하거나" >&2
  echo "    2. vercel preview로 테스트 후 vercel --prod 실행" >&2
  echo "" >&2
fi

# === L0: API Contract 검증 (THOROUGH only) ===
if [ "$TIER" = "THOROUGH" ] && [ -f "scripts/verify-dto-mapping.py" ]; then
  echo "  [L0] API Contract 검증 중..." >&2
  DTO_OUTPUT=$(python3 scripts/verify-dto-mapping.py 2>&1)
  if echo "$DTO_OUTPUT" | grep -qiE "ERROR|FAIL|mismatch"; then
    ERRORS+="[API CONTRACT]\n$(echo "$DTO_OUTPUT" | head -10)\n\n"
    echo "  ! API Contract 불일치 감지 (경고)" >&2
    # 경고만, BLOCK하지 않음
  else
    echo "  o API Contract 통과" >&2
  fi
fi

# === Self-Challenge: 완료 전 자가 검증 (THOROUGH only) ===
if [ "$TIER" = "THOROUGH" ] && [ "$FILE_COUNT" -gt 5 ]; then
  if [ ! -f ".completion-check.md" ] && [ ! -f "docs/.completion-check.md" ]; then
    if [ "$FILE_COUNT" -gt 10 ]; then
      # 10개 초과: BLOCK
      GATE_FAILED=1
      ERRORS+="[SELF-CHALLENGE] ${FILE_COUNT}개 파일 커밋. .completion-check.md (QA HARD/SOFT/미구현 표) 필수.\n\n"
      echo "  x [Self-Challenge] ${FILE_COUNT}개 파일 — .completion-check.md 없이 커밋 불가" >&2
    else
      # 5~10개: WARNING
      echo "  ⚠️ [Self-Challenge] ${FILE_COUNT}개 파일. .completion-check.md 작성 권장." >&2
    fi
  else
    echo "  o Self-Challenge 검증 파일 확인됨" >&2
  fi
fi

# --- 게이트 판정 ---
if [ $GATE_FAILED -eq 1 ]; then
  echo "" >&2
  echo "--- Commit Gate BLOCKED [$TIER] ---" >&2
  echo "아래 에러를 수정한 후 다시 커밋하세요:" >&2
  echo -e "$ERRORS" >&2
  exit 2
fi

echo "  o 모든 검증 통과 [$TIER]" >&2
exit 0
