import fs from 'fs'; import path from 'path'; import os from 'os';
import Database from 'better-sqlite3';
import * as sqliteVec from 'sqlite-vec';
const REPO='/Users/jung-wankim/Project/Claude/memory-bank';
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'mb-r17-'));
process.env.MEMORY_BANK_DB_PATH=path.join(tmp,'db.sqlite');
const { initDatabase, insertExchange } = await import(REPO+'/dist/db.js');
const { searchConversations } = await import(REPO+'/dist/search.js');
const db=initDatabase();
const emb=Array(384).fill(0.03);
insertExchange(db, {id:'VALID',project:'t',timestamp:new Date().toISOString(),userMessage:'staleterm valid doc',assistantMessage:'x',archivePath:'/tmp/y.jsonl',lineStart:1,lineEnd:2}, emb);
// 고아 posting 주입: exchanges에 없는 rowid로 FTS에 직접 삽입 (인덱스 오염 시뮬레이션)
const ins = db.prepare(`INSERT INTO exchanges_fts(rowid, user_message, assistant_message) VALUES (?, ?, ?)`);
for (let i=0;i<250;i++) ins.run(1000000+i, 'staleterm orphan '+i, 'x');
db.close();
const r = await searchConversations('staleterm', { limit:1, mode:'text' });
const ok = r.length===1 && r[0].exchange.id==='VALID';
console.log((ok?'✅':'❌'), `R17: 고아 posting 250개 속에서 유효 매치 반환 (${r.length}건, ${r[0]?.exchange.id??'없음'})`);
fs.rmSync(tmp,{recursive:true,force:true});
process.exit(ok?0:1);
